version: '3.7'

services:
  coop_api:
    image: node:latest
    container_name: coop_api
    restart: always
    build: 
      context: ./
      dockerfile: dockerfiles/Dockerfile.dev.server
    links:
      - coop_db
    env_file:
      - ./envfiles/server.dev.env
    ports:
      - "1433:8000"

  coop_db:
    image: postgres:12
    container_name: coop_db
    restart: always
    build: 
      context: ./
      dockerfile: dockerfiles/Dockerfile.dev.db
    env_file:
      - ./envfiles/db.dev.env
    logging:
      options:
        max-size: '10m'
        max-file: '5'
    volumes:
      # Copy SQL files to the container at build time
      - ./sql/:/docker-entrypoint-initdb.d/

