version: '3.7'

services:
  database-api:
    image: node:latest
    container_name: database-api
    restart: always
    build: 
      context: ./
      dockerfile: Dockerfile.server
    links:
      - db
    environment:
      - HOST_PORT=1433
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=post1234
      - DB_NAME=wcfc_db

    ports:
      - "1433:8000"
    

  db:
    image: postgres:12
    container_name: db
    restart: always
    build: 
      context: ./
      dockerfile: Dockerfile.db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=post1234
      - POSTGRES_DB=wcfc_db
      - DB_USER=admin
      - DB_PASS=post1234
    logging:
      options:
        max-size: '10m'
        max-file: '5'
    volumes:
      # Copy SQL files to the container at build time
      - ./sql/:/docker-entrypoint-initdb.d/

volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog: 
    driver: local
  
