version: '3.7'

services:
  db:
    image: postgres:12
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${PUSER}
      - POSTGRES_PASSWORD=${PPASS}
      - POSTGRES_DB=${PDB}
    logging:
      options:
        max-size: '10m'
        max-file: '5'
    volumes:
      # Mount the Docker host's `/data` directory to the container at `/var/lib/postgresql/data`
      - ./data:/var/lib/postgresql/data
      # Copy SQL files to the container at build time
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - "5432:5432"
    networks:
      - default
      
networks:
  default:
    driver: bridge