version: '3.7'

services:
  db:
    image: postgres:12
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${PUSER}
      - POSTGRES_PASSWORD=${PPASS}
      - POSTGRES_DB=${PDB}
      - POSTGRES_HOST=${PHOST}
    logging:
      options:
        max-size: '10m'
        max-file: '5'
    volumes:
      # Copy SQL files to the container at build time
      - ./sql/:/docker-entrypoint-initdb.d/
      
    ports:
      - "$PHOST:5432:5432"
    networks:
      - default
      
networks:
  default:
    driver: bridge