FROM node:slim AS node_base

RUN echo "NODE Version:" && node --version
RUN echo "NPM Version:" && npm --version

FROM postgres:12
COPY --from=node_base / /

# Establish working directory
WORKDIR /usr/src/app

# Copy the application files over to the container
COPY ./server/ ./server/

# CD into the application directory
WORKDIR /usr/src/app/server

# install dependencies
RUN npm install express body-parser pg@8.7.1 cors
    
CMD [ "node" , "index.js" ]

