FROM node:latest AS node_base

RUN echo "NODE Version:" && node --version
RUN echo "NPM Version:" && npm --version

FROM postgres:12
COPY --from=node_base / /

# Establish working directory
WORKDIR /usr/src/app

# Copy the application files over to the container
COPY ./server/ ./server/

# CD into the application directory
WORKDIR /usr/src/app/server

# install dependencies
# RUN curl -sL https://deb.nodesource.com/setup | sudo bash - && \
#     apt-get install -yq nodejs build-essential && \
#     npm install -g npm

# RUN npm install npm@latest -g && \
#     npm install n -g && \
#     n latest

RUN npm install express body-parser pg@8.7.1
    
CMD [ "node" , "index.js" ]

